// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WamBot.Data;

#nullable disable

namespace WamBot.Migrations
{
    [DbContext(typeof(WamBotDbContext))]
    [Migration("20240826203452_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WamBot.Data.Canvas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Canvases");
                });

            modelBuilder.Entity("WamBot.Data.MemberInfo", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanvasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("CanvasId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("WamBot.Data.Canvas", b =>
                {
                    b.OwnsMany("WamBot.Data.Layer", "Layers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BlendingMode")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CanvasId")
                                .HasColumnType("INTEGER");

                            b1.Property<byte[]>("LayerData")
                                .HasColumnType("BLOB");

                            b1.Property<double>("Opacity")
                                .HasColumnType("REAL");

                            b1.Property<int>("Position")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("CanvasId");

                            b1.HasIndex("Position");

                            b1.ToTable("Layer");

                            b1.WithOwner()
                                .HasForeignKey("CanvasId");
                        });

                    b.Navigation("Layers");
                });

            modelBuilder.Entity("WamBot.Data.MemberInfo", b =>
                {
                    b.HasOne("WamBot.Data.Canvas", "Canvas")
                        .WithMany()
                        .HasForeignKey("CanvasId");

                    b.OwnsOne("WamBot.Data.ColorInfo", "Color", b1 =>
                        {
                            b1.Property<ulong>("MemberInfoGuildId")
                                .HasColumnType("INTEGER");

                            b1.Property<ulong>("MemberInfoUserId")
                                .HasColumnType("INTEGER");

                            b1.Property<byte>("B")
                                .HasColumnType("INTEGER");

                            b1.Property<byte>("G")
                                .HasColumnType("INTEGER");

                            b1.Property<byte>("R")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MemberInfoGuildId", "MemberInfoUserId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberInfoGuildId", "MemberInfoUserId");
                        });

                    b.Navigation("Canvas");

                    b.Navigation("Color");
                });
#pragma warning restore 612, 618
        }
    }
}
